'use strict';

module.exports = {
    INVALID_AUTHTYPE: 'invalid auth type',
    UNKNOWN_USER: 'unknown user',
    INVALID_CREATE_GROUP_VALUES: 'invalid create group values',
    INVALID_REQUEST_BODY: 'invalid request body',
    DB_ERROR: 'database error',
    MISSING_AUTH_HEADER: 'missing http request header Authorization',
    INVALID_AUTH_HEADER: 'invalid http request header Authorization provided',
    INVALID_AUTH_TOKEN: 'invalid authToken',
    UNKNOWN_USER_OR_EXPIRED_TOKEN: 'unknown user or expired token',
    MINIO_ERROR: 'minio error',
    INVALID_OR_MISSING_FILE_IN_REQUEST: 'invalid or missing file in request',
    INVALID_OR_MISSING_FILENAME_IN_REQUEST: 'invalid or missing filename in request',
    MINIO_NO_SUCH_BUCKET: 'NoSuchBucket',
    MISSING_ID_IN_URL: 'missing ID in URL',
    USER_NOT_IN_GROUP: 'user is not a member of the group',
    UNKNOWN_GROUP: 'unknown group',
    NOT_AUTHENTICATED: 'user is not authenticated',
    DUPLICATED_USER: 'duplicated user',
    SEND_FCM_FAILED: 'failed to send push notification via firebase cloud messaging',
    INVALID_CREATE_TRANSACTION_VALUES: 'invalid create transaction values',
    INVALID_DATE_FORMAT: 'invalid date format',
    NO_USERS: 'no users',
    RESOURCE_NOT_FOUND: 'resource not found',
    INVALID_JSON: 'invalid json',
    UNCAUGHT_ERROR: 'uncaught error',
    INVALID_SPLIT: 'invalid split',
  };
