version: '2'
services:
  mongo:
    image: mongo
    volumes:
      - /data:/data/db
    # map port to be accessible from extern (dev-only)
    ports:
      - "27017:27017"
    # Wrong direction of dependency on purpose, due to test the reconnect functionality of the backend
    links:
      - backend
  backend-test:
    build: ./backend-test
    depends_on:
      - backend
    volumes:
      - ./backend:/app
  backend:
    build: ./backend
    image: localhost:5000/backend
    ports:
      - "8081:8081"
  production-server:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 8088:80
