version: '2.1'
services:
  mongo:
    build: ./mongo
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/debtsquared --quiet
      interval: 1s
      timeout: 1s
      retries: 12

  object-storage:
    build: ./minio
    healthcheck:
      test: 'curl -H "User-Agent: Mozilla" -s -k -o /dev/null -I -w "%{http_code}" http://localhost:9000/minio/index.html | grep 200'
      interval: 1s
      timeout: 1s
      retries: 12

  backend:
    environment:
      - ORIGINS=https://localhost:8088::::http://localhost:80::::http://localhost
      - LOGLEVEL=error
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918
      - ADMIN_EMAIL=admin@example.com
      - FCM_SERVER_KEY=AAAA03Mtpdk:APA91bGy9qAosK5suZI3ctH2mhYbtyS1f7pXajkaPePTuZ58IiZcYy_2PUlpwfXnuqck9KZIXDZvDzvJyfgg7uJS5YJsy5uIYjOXTTxhapMhbtjBfimnbDYA3nJAN76-XVU--g0KVoLM
      - PORT=8081
      - MONGODB_URL=mongodb://mongo/debtsquared
      - GOOGLE_OAUTH_CLIENT_ID=908170470873-8151s7cvldroebdl7mcpg2houdgljgfg.apps.googleusercontent.com
      - FACEBOOK_URL_APP_TOKEN=1971379956470536%7ChIQ5dRDon3DJq2YzH1NU41byB-w
      - JWT_SIMPLE_SECRET=A3xFr93Yl2qTn5
      - MINIO_ENDPOINT=object-storage
      - MINIO_ENDPOINT_PORT=9000
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - MINIO_BUCKET_NAME=bucket
      - MINIO_OBJECT_PREFIX=public
    image: localhost:5000/backend
    depends_on:
      mongo:
        condition: service_healthy
      object-storage:
        condition: service_healthy
    healthcheck:
      test: wget -O - http://localhost:8081/v1/status || exit 1
      interval: 1s
      timeout: 1s
      retries: 12

  backend-testing:
    build: ./backend/testing-api
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=inter@kt!veMedien
      - ADMIN_EMAIL=admin@example.com
      - FACEBOOK_URL_APP_TOKEN=1971379956470536%7ChIQ5dRDon3DJq2YzH1NU41byB-w
      - FACEBOOK_APP_ID=1971379956470536
    depends_on:
      backend:
        condition: service_healthy
