version: '2.1'
services:
  mongo:
    build: ./mongo
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/debtsquared --quiet
      interval: 1s
      timeout: 1s
      retries: 12

  object-storage:
    build: ./minio
    healthcheck:
      test: 'curl -H "User-Agent: Mozilla" -s -k -o /dev/null -I -w "%{http_code}" http://localhost:9000/minio/index.html | grep 200'
      interval: 1s
      timeout: 1s
      retries: 12

  backend:
    environment:
      - ORIGIN=http://localhost:8088
      - LOGLEVEL=error
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=inter@kt!veMedien
      - ADMIN_EMAIL=admin@example.com
      - FCM_SERVER_KEY=AAAA03Mtpdk:APA91bGy9qAosK5suZI3ctH2mhYbtyS1f7pXajkaPePTuZ58IiZcYy_2PUlpwfXnuqck9KZIXDZvDzvJyfgg7uJS5YJsy5uIYjOXTTxhapMhbtjBfimnbDYA3nJAN76-XVU--g0KVoLM
    image: localhost:5000/backend
    depends_on:
      mongo:
        condition: service_healthy
      object-storage:
        condition: service_healthy
    healthcheck:
      test: wget -O - http://localhost:8081/v1/status || exit 1
      interval: 1s
      timeout: 1s
      retries: 12

  backend-testing:
    build: ./backend/testing-api
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=inter@kt!veMedien
      - ADMIN_EMAIL=admin@example.com
    depends_on:
      backend:
        condition: service_healthy
