version: '2.1'
services:
  mongo:
    build: ./mongo
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/debtsquared --quiet
      interval: 1s
      timeout: 1s
      retries: 12

  object-storage:
    build: ./minio
    healthcheck:
      test: 'curl -H "User-Agent: Mozilla" -s -k -o /dev/null -I -w "%{http_code}" http://localhost:9000/minio/index.html | grep 200'
      interval: 1s
      timeout: 1s
      retries: 12

  backend:
    environment:
      - ORIGIN=http://localhost:8088
    image: localhost:5000/backend
    depends_on:
      mongo:
        condition: service_healthy
      object-storage:
        condition: service_healthy
    healthcheck:
      test: wget -O - http://localhost:8081/v1/version || exit 1
      interval: 1s
      timeout: 1s
      retries: 12

  backend-testing:
    build: ./backend/testing-api
    depends_on:
      backend:
        condition: service_healthy
