version: '2'
services:
  mongo:
    image: mongo
    volumes:
      - /data:/data/db
  object-storage:
    build: ./minio
    volumes:
      - /minio-data:/data
    ports:
      - "9000:9000"
  backend:
    build: ./backend
    image: localhost:5000/backend
    ports:
      - "8081:8081"
    depends_on:
      - mongo
      - object-storage
  web:
    build: 
      context: ./frontend
      args:
        - WEB_SERVICE_URL=http://localhost:8081
    image: localhost:5000/frontend
    ports:
      - 8088:80
    depends_on:
      - backend
