version: '2.1'
services:
  mongo:
    build: ./mongo
    volumes:
      - /data:/data/db
    ports: 
      - "27017:27017"
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/debtsquared --quiet
      interval: 1s
      timeout: 1s
      retries: 12

  object-storage:
    build: ./minio
    volumes:
      - /minio-data:/data
    ports:
      - "9000:9000"
    healthcheck:
      test: 'curl -H "User-Agent: Mozilla" -s -k -o /dev/null -I -w "%{http_code}" http://localhost:9000/minio/index.html | grep 200'
      interval: 1s
      timeout: 1s
      retries: 12

  backend: 
    build: ./backend 
    environment: 
      - ORIGIN=http://localhost:8088
      - LOGLEVEL=debug
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=inter@kt!veMedien
      - ADMIN_EMAIL=admin@example.com
      - FCM_SERVER_KEY=AAAA03Mtpdk:APA91bGy9qAosK5suZI3ctH2mhYbtyS1f7pXajkaPePTuZ58IiZcYy_2PUlpwfXnuqck9KZIXDZvDzvJyfgg7uJS5YJsy5uIYjOXTTxhapMhbtjBfimnbDYA3nJAN76-XVU--g0KVoLM
      - PORT=8081
      - MONGODB_URL=mongodb://mongo/debtsquared
      - GOOGLE_OAUTH_CLIENT_ID=908170470873-8151s7cvldroebdl7mcpg2houdgljgfg.apps.googleusercontent.com
      - FACEBOOK_URL_APP_TOKEN=1971379956470536%7ChIQ5dRDon3DJq2YzH1NU41byB-w
      - JWT_SIMPLE_SECRET=A3xFr93Yl2qTn5
      - MINIO_ENDPOINT=object-storage
      - MINIO_ENDPOINT_PORT=9000
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - MINIO_BUCKET_NAME=bucket
      - MINIO_OBJECT_PREFIX=public
    image: localhost:5000/backend
    ports:
      - "8081:8081"
    depends_on:
      mongo:
        condition: service_healthy
      object-storage:
        condition: service_healthy
    healthcheck:
      test: wget -O - http://localhost:8081/v1/status || exit 1
      interval: 1s
      timeout: 1s
      retries: 12

  web:
    build: 
      context: ./frontend
      args: 
        - WEB_SERVICE_URL=http://localhost:8081
    image: localhost:5000/frontend
    ports:
      - 8088:80
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: wget -O - http://localhost:80/ || exit 1
      interval: 1s
      timeout: 1s
      retries: 12

  lighthouse:
      build:
        context: ./lighthouse
      environment: 
        - URL=http://web:80/#/
        - AUDIT_NAME=report.json
      volumes:
        - /lighthouse_reports:/results
      image: localhost:5000/lighthouse
      depends_on:
        web:
          condition: service_healthy
     