version: '2'
services:
  mongo:
    image: mongo
    volumes:
      - /data:/data/db
    # map port to be accessible from extern (dev-only)
    ports:
      - "27017:27017"
    # Wrong direction of dependency on purpose, due to test the reconnect functionality of the backend
    links:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    image: localhost:5000/backend
    # environment:
    #   NODE_ENV: production
    ports:
      - "8081:8081"
  web-production:
    build: ./frontend
    image: localhost:5000/frontend
    depends_on:
      - backend
    ports:
      - 8088:80
