pipeline {
    agent any
    stages {
        stage('Checkout code') {
            steps {
                git credentialsId: '3ccd0e84-c917-4b30-b440-016c57545b2d', url: 'git@gitlab.mi.hdm-stuttgart.de:bk095/InteraktiveMedien.git'
                sh 'ls'
            }
        }

        stage('Generate doc') {
            steps {
                sh 'docker build -f backend/doc/Dockerfile -t apidoc:latest backend'
                sh 'docker run apidoc:latest'
                sh 'docker cp $(docker ps --latest --format "{{.ID}}"):/doc ./generated_doc'
            }
        }

        stage('Publish doc') {
            steps {
                publishHTML( [allowMissing: false,
                    alwaysLinkToLastBuild: false,
                    keepAll: false,
                    reportDir: 'generated_doc',
                    reportFiles: 'index.html',
                    reportName: 'ApiDocs',
                    reportTitles: ''])
            }
        }
    }
}