pipeline {
    agent any
    stages {
        stage('Checkout code') {
            steps {
                git credentialsId: '3ccd0e84-c917-4b30-b440-016c57545b2d', url: 'git@gitlab.mi.hdm-stuttgart.de:bk095/InteraktiveMedien.git'
                sh 'ls'
            }
        }

        stage('Generate doc') {
            agent {dockerfile {
                dir  'backend'
                additionalBuildArgs '-f <doc/Dockerfile>'}
            }
            steps {
                sh 'gulp apidoc'
            }
        }
    }
}