execution:
- concurrency: 5
  throughput: 25
  ramp-up: 2m
  steps: 5
  hold-for: 2m
  scenario: scenario1

  locations:
    eu-west-1: 2

scenarios:
  scenario1:
    retrieve-resources: false
    requests:
      - http://cloudproject.mi.hdm-stuttgart.de/

reporting:
- module: passfail
  criteria:
  - avg-rt>5000ms for 5s, stop as failed

provisioning: cloud

modules:
  cloud:
    timeout: 10s  # BlazeMeter API client timeout
    browser-open: none  # auto-open browser on test start/end/both/none
    check-interval: 5s  # interval which Taurus uses to query test status from BlazeMeter