execution:
- concurrency: 5
  throughput: 25
  ramp-up: 2m
  steps: 5
  hold-for: 2m
  scenario: scenario1

  locations:
    eu-west-1: 2
    us-east-1: 1

scenarios:
  scenario1:
    retrieve-resources: false
    requests:
      - http://localhost:80/

reporting:
- module: passfail
  criteria:
  - avg-rt>5000ms for 5s, stop as failed

provisioning: cloud

modules:
  cloud:
    test: https://a.blazemeter.com/app/#/accounts/234064/workspaces/228106/projects/291563/tests/6159497